theme = "edge_default"

[editor]
line-number = "relative"
mouse = false

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.lsp]
auto-signature-help = false

[editor.file-picker]
hidden = false
